{% set name = "nxviz" %}
{% set version = "0.3.2" %}
{% set sha256 = "2b8802305eed2cec3d64ffdc90cf94ceb7b9447bc6dd1cf6f3a65078cbae2877" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt
  skip: True  # [py<35]

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - matplotlib
    - networkx
    - numpy
    - palettable

test:
  imports:
    - nxviz
    - nxviz.plots
    - nxviz.geometry
    - nxviz.utils

about:
  home: http://github.com/ericmjl/nxviz
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Rational network visualizations in Python'

  dev_url: https://github.com/ericmjl/nxviz

extra:
  recipe-maintainers:
    - ericmjl
