{% set name = "nxviz" %}
{% set version = "0.6.3" %}
{% set sha256 = "56405ceb1b95a540b3feca387f6f2f30a7e96725bc65fccd9488acf1849af96f" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt
  skip: true  # [py<36]

requirements:
  host:
    - python
    - setuptools
  run:
    - python
    - matplotlib-base
    - networkx
    - numpy
    - palettable
    - seaborn
    - more-itertools

test:
  imports:
    - nxviz
    - nxviz.plots
    - nxviz.geometry
    - nxviz.utils

about:
  home: http://github.com/ericmjl/nxviz
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Rational network visualizations in Python

  dev_url: https://github.com/ericmjl/nxviz

extra:
  recipe-maintainers:
    - ericmjl
