travis:
  secure:
    BINSTAR_TOKEN: maACLhg2odWGyLUuG/FNPINs0ElV9GmINPZTx3Jsir3wSTReSJXiUG1rGh87Ck+Eq3Z6++dAmjg6m4QY5l5AyXktUWxM85xWkIaK67cQRcV8wpTxTUGMsW99HYQLlFBHAtoJMTAMnGoMQXFyw8jPvRAOLOfefQcWE9IYMv233/cjSTDHkaBJ/WnT2QGPZOGTpFCBUsgwMQUfwncNw8nf6ABwrW0uksCv3Mj2NH8n3MjwDWR6tUf58Opya6OmRYBEDjC1iOeg0gNeGtEYzXY8y7w6QWbG4eCKaCKVSlT1S6jAKg+IME6JiPX1X6TEQI/eUUwNL5NGjNBakP13PmPVE9bnlEtHJLCuSbTin57/48S41uP4qfrtbu/UoG9Jr3k772DaSlOSNPWTvzC2kNJo+ClnneViLa7uHhQmBbu1hhZIE6rgI3WDSVNrREnXdUGLRvAdxSSKMPJ/+/6IjHF5lIb1dl3aJKWe5WeBMnU10AQpRxSF/34nQrLG5Vnge3TOEaJJ+IUVr2G40hoc71kQ5V3nQzkFRd7fUY/o/g+3i7bu8iGya1ypTdGjUkzMf1VR8QgM+KoqkmyyfBDlX3+nd6alWuUPxIxNutb0E/NajYOiMLQEKyamedNvsxif6dCL+BAKMEYtJ2Ckuh5hB2wv1NPucEOqKJkA3IFvBfogHkc=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
