appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: uzTS8vnUMBccmnmngNDkQv7wV0MmuZUej7aVi/B1qwndcbNoROe/pI4PnW67P2vo6wV5gWmgZCIq/4xhmgOSbYlT24vTXRehFH9U8GAtZAK9h37jsmthnKyYmktbHkYZsaiPjl0JXVE1xIh1epF/prVpA5hUaDiu+DwJGbCXYRtPnln9o8zcanaXyG+ELCx65rslaKx82QOi2tlaAZ7ecNROBzAjVPLeqbM73N7mlxmnVZbDEqw6oQvzf1Vygk0wYXS/KxQDI6DPN3q1TQLE9CTjoUMCvvbisCB3Xsvq9NiVFQkvHSOoC98WT67e2S+BCRWffX65vuLa0Y94McM+8atfQGG+EoKDOl+ydIpQj6KEVex2kN1QfZR6/CZL64tmvpxBa038bxt9jzK0tiVaV8nqUXahhJS6StiQxiaRr7epwmyzGkHk1w3UQeU56bfkwB5EFfvLVQB0+6f3jY3BUBikVDzIo4cP6Y+mAlEIcK/ZoqAQ5bOWXE9eMhayiNwR6Qh4+hLp0PuGEpPgVXwJDNpQ+3S1fHNNTSiFSkICAz8j418xkYWPjf11id8jeNPtbC5nBRo+0PDSokaYkqtjd2jl+qOVItYWYqNf2oYTz2d2FJc6jAMsgZN5NkgwUxVYdxL++edX09vw/vnKjB4e9s6HQNRWiyc3r7s3Rrd33Gg=}
